# Generated by Django 2.2.3 on 2019-07-25 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_userextension'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.TextField(default='luoqijun'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.TextField(default='Jonery'),
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(default='Jonery', on_delete=django.db.models.deletion.CASCADE, related_name='author_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
