# Generated by Django 2.2.3 on 2019-07-25 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_chat_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='id',
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='room_name',
            field=models.TextField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userextension',
            name='portait',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userextension',
            name='rooms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_member', to='chat.ChatRoom'),
        ),
    ]
