# Generated by Django 2.2.3 on 2019-07-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20190725_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextension',
            name='rooms',
        ),
        migrations.AddField(
            model_name='userextension',
            name='rooms',
            field=models.ManyToManyField(null=True, related_name='group_member', to='chat.ChatRoom'),
        ),
    ]
