# Generated by Django 2.2.3 on 2019-07-25 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20190725_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextension',
            name='rooms',
        ),
        migrations.AddField(
            model_name='userextension',
            name='rooms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_member', to='chat.ChatRoom'),
        ),
    ]
