# Generated by Django 2.2.3 on 2019-07-25 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20190725_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userextension',
            old_name='portait',
            new_name='portrait',
        ),
    ]
