# Generated by Django 2.2.3 on 2019-07-25 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_auto_20190725_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userextension',
            options={},
        ),
        migrations.AlterModelManagers(
            name='userextension',
            managers=[
            ],
        ),
    ]
