# Generated by Django 2.2.3 on 2019-07-23 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_work', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_time']},
        ),
    ]
